anki.prod3.0/config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  get 'profile/show'
  
  get 'profile/faq'

  devise_for :users
  get 'decks/index'

  get 'decks/new'

  get 'decks/load_from_apkg'

  get 'decks/edit'
  get 'decks/repackage'

  get 'decks/reset'

  get 'cards/index'

  get 'cards/view'

  get 'cards/show'

  get 'cards/download_in_cards'
  match '/cards/:filename' => 'cards#sendimg', via: :get 
  match '/cards/:id/edit' => 'cards#edit', via: :get
  match '/cards/:id/:filename' => 'cards#sendimg', via: :get 

  mount Ckeditor::Engine => '/ckeditor'
  resources :cards 

   resources :decks do
    collection do
      get 'load_from_apkg'
    end
   end 
  
  root :to => 'decks#index'

	devise_scope :user do
		get "/login" => "devise/sessions#new"
	      end 
  
	devise_scope :user do
		delete "/logout" => "devise/sessions#destory"
	end

end

anki.prod3.0/app/models/card.rb
class Card < ActiveRecord::Base
  # Card model 
  belongs_to :deck
  #has_many :deck

  # For CKEditor, updates individual card database values
  delegate :id, :to => :deck_id, :prefix => true
	def update_card(front, back)
  	front = front.gsub! "\r", ""
  	front = front.gsub! "\n", ""
  	back = back.gsub! "\r", ""
  	back = back.gsub! "\n", ""
		self.card_front = front
		self.card_back  = back
  	save
  end

  # For incrementing deck database values
  def increment(attribute, by = 1)
    self[attribute] ||= 0
    self[attribute] += by
    self
  end

  # For incrementing deck database values
  def increment!(attribute, by = 1)
    increment(attribute, by).update_attribute(attribute, self[attribute])
  end

end

anki.prod3.0/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  # Shows all cards
  def index
    @cards = Card.all   
  end

  # Shows selected cards when "View" button is clicked on homepage
  def edit
    @card = Card.find(params[:id])
  end

  # Redirect so that when viewing cards, user can download the viewed deck
  def download_in_cards
    redirect_to  decks_repackage_path(:id =>@deck.id), notice: "Finished."    
  end

  # modified by Vamsi Koduru, Dec 10, 2014
  def show
    # let us rember the deck_id of the cards shown
    # we need deck_id to dynamically serve the image files to the
    # browser. We save the deck_id passed as :id param into the session
    # and that variable will be used by sendimg when the sendimg is called
    # to serve a specific image of the cards that belong to the deck_id
    session[:deck_id] = params[:id]
    # list all cards for the given deck
    @cards = Card.where(deck_id: params[:id])
  end

  # Added by Vamsi Koduru, Dec 10, 2014
  # when the raw files are served by ActionView renderer all image files are
  # served through GET /cards/:filename where :filename is the name of the image file
  # we mapped the routes through
  # match 'cards/:filename' =>  'cards#sendimg', via: :get
  # in config/routes.rb
  # added following method to the image serving. We will use send_file 
  # to send the image file directly to the browser.
  def sendimg
    # which deck? get the deck_id we stored in the session
    deck_id = session[:deck_id]
    # construct the image file path name by prefix Rails.root to
    # Staging/{deck_id}/img_filename.jpg 
    directory_name = "Staging/" + deck_id.to_s
    img_filename = params[:filename]+".jpg"
    # now we have the fully qualified filename for the image file.
    # send this file to the browser using the send_file command.
    send_file Rails.root.join(directory_name, img_filename), 
				type: "image/jpg", disposition: "inline"
  end

  # Updating cards
  # Also increments user's edit count
  def update
    @user = User.find(current_user)
    @card = Card.find(params[:id])
     deck_id = session[:deck_id] 
     cfront = params[:card][:card_front]
     cback  = params[:card][:card_back]
    if @card.update_card(cfront, cback)
      @user.increment!(:ecounter)
      redirect_to cards_show_path(:id => deck_id), notice: "Card has been successfully edited."
    else
      render action: "edit"
    end  
  end

  private
  
    def card_params
      params.require(:card).permit( :card_front, :card_back)
    end

end

anki.prod3.0/app/helpers/cards_helper.rb
module CardsHelper
end

anki.prod3.0/app/views/cards/_form.html.erb
<% if @card.errors.any? %>
  <ul>
    <%= @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @card do |f| %>
  <!--<div>-->
    <!--<%= f.label :title %>-->
    <h3>Edit Card Front</h3>
 <!-- </div>-->
  <div>
    <%= f.cktext_area :card_front, rows: 20 %>
  </div>
  </br>
  <h3>Edit Card Back </h3>
  <div>
    <%= f.cktext_area :card_back, rows: 20 %>
  </br>
  <div>
    <%= f.submit %>
  </div>
<% end %>

anki.prod3.0/app/views/cards/edit.html.erb
<div class="page-header" style="margin-bottom: 20px;">
  <div class="row">
    <div class="col-md-4" style="text-align:left;">
      <div id="user_nav">
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "btn btn-danger" %>
          <%= current_user.email %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
      <div>
        <%= link_to "Informatics Report", profile_show_path %>
      </div>
    </div>
    <div class="col-md-3" style="padding:0px; text-align:right;">
      <p>
        <%= link_to "Homepage", "/", class: "btn btn-primary" %>
      </p>
    </div>
    <div class="col-md-2" style="padding:0px; text-align:right;">
      <p>
        <%= link_to "Upload Decks", new_deck_path, class: "btn btn-primary" %>
      </p>
    </div>
    <div class="col-md-2" style="padding: 0px; text-align:right;">
      <p>
        <%= link_to "Account Settings",  profile_index_path, class: "btn btn-primary" %>
      </p>
    </div>
    <div class="col-md-1" style="padding: 0px; text-align:right;">
      <p>
        <%= link_to "FAQ", profile_faq_path, target: '_blank', class: "btn btn-primary" %>
      </p>
    </div>
  </div>
</div>

<center>

<%= link_to(image_tag("http://i.imgur.com/v8qikwv.png", :size=>"500x100", :alt=>"Ankishare Home", :title=>"Home", :controller=>"decks_controller", :action=>"index"),"/")%>

</center>

<%= link_to "Back to Deck", :back, class: "btn btn-primary" %>
<%= render "form" %>

anki.prod3.0/app/views/cards/index.html.erb
<center>
  <h1> Deck Title </h1>
</center>
<div style = "text-align: right">
  <%= link_to "Home", decks_path %>
</div>
<!-- http://stackoverflow.com/questions/17532171/changing-images-relative-path-to-full-url-in-refinerycms-blog -->
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th> Flashcard Front </th>
      <th> Flashcard Back </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= raw card.card_front %></td>
        <td><%= raw card.card_back %></td>
        <td><%= link_to "Edit Card",{:id => card.id, :action => 'edit'} , class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

anki.prod3.0/app/views/cards/show.html.erb
<div class="page-header" style="margin-bottom: 20px;">
  <div class="row">
    <div class="col-md-4" style="text-align:left;">
      <div id="user_nav">
        <% if user_signed_in? %>
          Logged in as <%= current_user.email %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
      <div>
        <%= link_to "Informatics Report", profile_show_path %>
      </div>
    </div>
    <div class="col-md-3" style="padding:0px; text-align:right;">
      <p>
        <%= link_to "Homepage", "/", class: "btn btn-primary" %>
      </p>
    </div>
    <div class="col-md-2" style="padding:0px; text-align:right;">
      <p>
        <%= link_to "Upload Decks", new_deck_path, class: "btn btn-primary" %>
      </p>
    </div>
    <div class="col-md-2" style="padding: 0px; text-align:right;">
      <p>
        <%= link_to "Account Settings",  profile_index_path, class: "btn btn-primary" %>
      </p>
    </div>
    <div class="col-md-1" style="padding: 0px; text-align:right;">
      <p>
        <%= link_to "FAQ", profile_faq_path, target: '_blank', class: "btn btn-primary" %>
      </p>
    </div>
  </div>
</div>

<center>
  <%= link_to(image_tag("http://i.imgur.com/v8qikwv.png", :size=>"500x100", :alt=>"Ankishare Home", :title=>"Home", :controller=>"decks_controller", :action=>"index"),"/")%>
</center>
</br>
<center>
  <%= link_to "Download Deck", decks_repackage_path(:id => session[:deck_id]), class: "btn btn-primary" %>
</center>
</br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th> Flashcard Front </th>
      <th> Flashcard Back </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= raw card.card_front %></td>
        <td><%= raw card.card_back %></td>
        <td><%= link_to "Edit Card",{:id => card.id, :action => 'edit'} , class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>