ankishare1.6/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "upload" => "resumes#index", :as => "upload"

  resources :resumes, only: [ :index, :new, :create, :destroy]
  resources :users
  resources :sessions

  root "sessions#new"

end

ankishare1.6/app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader #Maybe change uploader type later on
 #this validates whether there is a value in the upload form
  validates :name, presence: true 
  validates :subject, presence: true
#  validates :class, presence: true  
end

ankishare1.6/app/models/user.rb
class User < ActiveRecord::Base

 # attr_accessible :email, :password, :password_confirmation
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A[\w+\-.]+@uci\.edu\z/i
 
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  
end

ankishare1.6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[ :user_id]) if session[ :user_id]
  end
end

ankishare1.6/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(upload_params)
    if @resume.save
      redirect_to resumes_path, notice: "#{@resume.name} has been uploaded."
    else
      render "new"
    end
  end
  
  def destroy
    @resume = Resume.find(params[ :id])
    @resume.destroy
    redirect_to resumes_path, notice: "#{@resume.name} has been deleted."
  end

  private
    def upload_params
      params.require(:resume).permit( :name, :subject, :attachment)
    end
end

ankishare1.6/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

 def create
    user = User.authenticate(params[ :email], params[ :password])
    if user
      session[ :user_id] = user.id
      redirect_to upload_url(@upload), :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[ :user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

ankishare1.6/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
  #each user has a user name, email, and password
  def user_params
    params.require( :user).permit( :username, :email, :password, :password_confirmation)
  end
end

ankishare1.6/app/helpers/application_helper.rb
module ApplicationHelper
end

ankishare1.6/app/helpers/resumes_helper.rb
module ResumesHelper
end

ankishare1.6/app/helpers/sessions_helper.rb
module SessionsHelper
end

ankishare1.6/app/helpers/users_helper.rb
module UsersHelper
end

ankishare1.6/app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

ankishare1.6/app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

ankishare1.6/app/views/resumes/index.html.erb
<style>
h2{
font-size: 35px;
font-family: Lucida Sans Unicode;
line-height:30%;

}
h3{
font-size: 35px;
font-family: Lucida Sans Unicode;
line-height:30%;
}
</style>

<h1>
<div align="center"><a href="ankishare.com"><img src="http://i.imgur.com/v8qikwv.png" title="Logo" width="1000" height="213"/></a></div></h1>
<br>
<br>
<br>
</div>

<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
  <p align="center">
  <%= link_to "Upload Decks", new_resume_path, class: "btn btn-primary" %>
  </p>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Class</th>
      <th>Subject</th>
      <th></th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td>Under Development</td>
        <td><%= resume.subject %></td>
        <td><%= link_to "Download Deck", resume.attachment_url %></td>
        <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

ankishare1.6/app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label :name %><br />
    <%= f.text_field :name %> <br />
    <%= f.label :subject %><br />
    <%= f.text_field :subject %><br />
    <!--<%= f.label :class %><br />-->
    <!--<%= f.text_field :class %><br />-->
    <%= f.label :attachment %><br />
    <%= f.file_field :attachment %> <br />
    <%= f.submit "Upload", class: "btn btn-primary" %>
  <% end %>
</div>